const MESSAGES: Readonly<Record<string, string>> = {
  'coordinating-session-already-live': 'Ya hay una sesión coordinadora en marcha.',
  'coordinating-session-opening': 'La sesión coordinadora todavía se está abriendo.',
  'coordinating-session-working': 'La sesión coordinadora está trabajando. Espera a que termine el turno y vuelve a intentarlo.',
  'coordinating-session-awaiting-permission': 'La sesión coordinadora está esperando un permiso en su terminal. Respóndelo y vuelve a intentarlo.',
  'coordinating-session-turn-not-finished': 'No se sabe qué está mostrando la terminal de la sesión. Espera a que termine un turno y vuelve a intentarlo.',
  'coordinating-session-not-live': 'La sesión coordinadora ya no está viva. Abre otra para seguir.',
  'coordinating-session-busy': 'La sesión coordinadora está realizando otra operación. Inténtalo de nuevo cuando termine.',
  'coordinating-session-target-changed': 'La sesión coordinadora ha cambiado. Actualiza la página antes de volver a intentarlo.',
  'coordinating-session-not-ended': 'La sesión coordinadora sigue viva: no hace falta reabrirla.',
  'coordinating-session-close-failed': 'El cierre de la sesión coordinadora falló. Termina de cerrarla antes de reabrirla.',
  'story-spec-frozen': 'Este ticket ya tiene su spec congelado, así que su brainstorming ha terminado. Sigue con el groom.',
  'malformed-id': 'El ticket no tiene un formato válido.',
  'malformed-path': 'La ruta local debe ser una ruta absoluta válida.',
  'checkout-not-confirmed': 'La ruta local no es un clon de git de un repositorio de GitHub.',
  'session-closure-not-recorded': 'No se pudo guardar el cierre de la sesión. Puedes volver a intentarlo.',
  'session-closure-not-understood': 'No se pudo interpretar el estado guardado del cierre. Puedes volver a intentarlo.',
  'session-not-terminated': 'No se pudo inspeccionar o terminar la sesión. Vuelve a intentarlo; las sesiones nuevas seguirán bloqueadas hasta confirmar el cierre.',
  'session-termination-unconfirmed': 'No se ha podido confirmar que la sesión haya terminado. Vuelve a intentarlo; las sesiones nuevas seguirán bloqueadas hasta verificar el cierre.',
  'session-termination-permission-denied': 'El sistema no tiene permisos para verificar o terminar la sesión. Corrige los permisos o pide a su propietario que termine la sesión original y vuelve a intentarlo. Las sesiones nuevas seguirán bloqueadas hasta verificar el cierre.',
  'session-ownership-unverifiable': 'No hay identidad original suficiente para terminar la sesión automáticamente. Cierra el terminal original si sigue disponible o pide a su propietario que confirme que terminó y vuelve a verificar. Las sesiones nuevas seguirán bloqueadas hasta confirmar el cierre.',
  'gate-not-from-the-page': 'Esta acción solo se puede realizar desde la página que sirve el backend.',
  'spec-not-freezable': 'El spec todavía no cumple las condiciones para congelarse.',
  'epic-spec-not-understood': 'No se ha podido interpretar el spec del epic.',
  'plan-changed': 'El plan ha cambiado. Revisa la versión nueva antes de volver a intentarlo.',
  'checkout-not-on-default-branch': 'La ruta local no está en la rama principal. Cámbiala a la rama principal y vuelve a abrir la sesión.',
  'checkout-not-up-to-date': 'La ruta local no se ha podido poner al día con la rama principal del remoto. Actualízala a mano y vuelve a abrir la sesión.',
  'workspace-not-read': 'git no ha podido leer la ruta local. Comprueba que es un clon válido y vuelve a intentarlo.',
  'workspace-not-understood': 'git ha respondido algo que no se ha podido interpretar al leer la ruta local.',
  'user-story-not-read': 'No se ha podido leer el ticket. Comprueba que existe y que la sesión de Jira o de GitHub está iniciada.',
  'user-story-not-understood': 'El ticket ha llegado en un formato que no se ha podido interpretar.',
  'nothing-to-plan': 'Falta el ticket: indica qué quieres planificar.',
  'conversation-not-started': 'No se ha podido arrancar Claude en la ruta local.',
  'conversation-not-recorded': 'No se ha podido guardar la conversación en disco. Revisa el espacio y los permisos del directorio de estado.',
  'session-hooks-not-written': 'No se ha podido escribir la configuración local de Claude (.claude/settings.local.json) en la ruta local.',
  'session-hooks-not-understood': 'La configuración local de Claude (.claude/settings.local.json) no es un objeto JSON válido. Corrígela y vuelve a intentarlo.',
  'no-epic-spec': 'Todavía no hay spec de ejecución para este ticket.',
  'epic-spec-not-read': 'El spec de ejecución existe, pero no se ha podido leer.',
  'epic-spec-not-written': 'No se ha podido guardar en disco el estado del spec.',
  'freeze-in-progress': 'Ya se está congelando el spec. Espera a que termine antes de volver a pulsar.',
  'spec-already-frozen': 'El spec ya está congelado.',
  'spec-not-frozen': 'El spec todavía no está congelado: congélalo en la puerta 1.',
  'epic-branch-not-published': 'No se ha podido publicar la rama del spec en el remoto.',
  'epic-branch-not-understood': 'git ha respondido algo que no se ha podido interpretar al preparar la rama del spec.',
  'epic-pull-request-not-opened': 'No se ha podido abrir la pull request del spec.',
  'pull-request-not-read': 'No se ha podido leer la pull request en GitHub.',
  'pull-request-not-understood': 'GitHub ha respondido algo que no se ha podido interpretar sobre la pull request.',
  'reslicing-in-progress': 'Ya se está publicando el nuevo troceado. Espera a que termine antes de volver a pulsar.',
  'groom-in-progress': 'El groom ya está en marcha. Espera a que termine antes de volver a pulsar.',
  'spec-resliced': 'El troceado ha cambiado en la sesión coordinadora. Publícalo y mergéalo antes de lanzar el groom.',
  'spec-not-published': 'El spec está congelado, pero todavía no está en la rama principal. Mergea su pull request y vuelve a intentarlo.',
  'epic-not-groomed': 'El groom ha fallado.',
  'groom-plan-not-understood': 'El plan del groom ha llegado en un formato que no se ha podido interpretar.',
  'published-spec-not-read': 'No se ha podido leer en GitHub el spec publicado.',
  'published-spec-not-understood': 'GitHub ha respondido algo que no se ha podido interpretar sobre el spec publicado.',
  'epic-issues-not-read': 'No se han podido leer las issues del milestone en GitHub.',
  'epic-issues-not-understood': 'GitHub ha respondido las issues del milestone en un formato que no se ha podido interpretar.',
  'epic-issues-uncertain': 'No se ha podido leer la lista completa de issues del milestone. Vuelve a intentarlo en un momento.',
  'no-epic-issues': 'El milestone todavía no tiene issues: lanza el groom primero.',
  'epic-partially-groomed': 'El milestone solo tiene parte de las issues previstas: termina el groom antes de autorizar.',
  'epic-issue-not-promoted': 'No se ha podido pasar una de las issues a lista para empezar. Vuelve a intentarlo.',
  'recover-plan-in-progress': 'Ya hay trabajo arrancando, recuperándose o limpiándose en este repositorio. Espera a que termine.',
  'recover-plan-not-found': 'Este trabajo ya no figura como activo.',
  'recover-plan-conflict': 'El estado actual del trabajo no permite recuperarlo.',
  'recover-plan-failed': 'No se ha podido leer el registro del trabajo para recuperarlo. Vuelve a intentarlo.',
  'recover-plan-unreadable': 'El registro del trabajo está dañado o es contradictorio, así que no se puede recuperar.',
  'cleanup-plan-in-progress': 'Ya hay trabajo arrancando, recuperándose o limpiándose en este repositorio. Espera a que termine.',
  'cleanup-plan-not-found': 'Este trabajo ya no figura como activo.',
  'cleanup-plan-conflict': 'El estado actual del trabajo no permite limpiarlo sin riesgo.',
  'cleanup-plan-failed': 'No se ha podido completar la limpieza del arranque fallido. Vuelve a intentarlo.',
  'cleanup-plan-unreadable': 'El registro del trabajo está dañado o es contradictorio, así que no se puede limpiar.',
}

const productError = (code: string, fallback: string): string => MESSAGES[code] ?? fallback

export { productError }
