import { describe, it, expect } from 'vitest'
import { mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, dirname } from 'node:path'
import { execFileSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { SERIALIZING_TOUCHES, selectNext, planDispatch } from '../scripts/dispatch.js'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const script = join(root, 'scripts', 'ct-init.sh')

// F11, part A. The success criterion is the same as that of the F6 round on
// the groom: somebody who only reads the repo has to be able to predict what
// `/ct-next` is going to do. The contract ct-init seeds covered the groom
// (what to write in the table) and almost nothing of the dispatch (what
// happens afterwards) — everything that follows is deducible from the plugin's
// code, but it reached no file of the target repo.
//
// Every assertion here corresponds to a REAL behaviour verified in the code;
// the tests that close the file tie down the claims that have an executable
// source of truth (the serialising touches) so that they cannot diverge in
// silence.
// #93 — the contract moved out of AGENTS.md into the governed repo's
// `docs/superpowers/CONTRATO-SLICES.md`. What this file watches is the TEXT of
// the contract, not which file it is pasted into, so the only thing that
// changes is where it is read from.
function seed() {
  const dir = mkdtempSync(join(tmpdir(), 'ct-'))
  execFileSync('bash', [script, dir], { encoding: 'utf8' })
  const contractText = readFileSync(join(dir, 'docs', 'superpowers', 'CONTRATO-SLICES.md'), 'utf8')
  rmSync(dir, { recursive: true, force: true })
  return contractText
}

const V1 = readFileSync(join(root, '__tests__', 'fixtures', 'slices-contract-v1.md'), 'utf8')
// V4: the block exactly as the plugin emitted it BEFORE F13 (hash
// 02247741…, already recorded in SLICES_PRISTINE_HASHES). It is the negative
// check of the F13 tests: it serves to show that the new claims were not there
// before, just as V1 is for those of F11.
const historicalBlockV4 = () => readFileSync(join(root, '__tests__', 'fixtures', 'slices-contract-v4.md'), 'utf8')
// V5: the block exactly as the plugin emitted it BEFORE F15 (hash cd59702d…,
// already recorded in SLICES_PRISTINE_HASHES; the fixture was generated by
// running the ct-init.sh of dac5326 and its hash matches, so it is the real
// block and not a transcription). Negative check of the F15 tests.
const historicalBlockV5 = () => readFileSync(join(root, '__tests__', 'fixtures', 'slices-contract-v5.md'), 'utf8')

// flat: the block without markdown bold and with the line breaks of the
// wrapping collapsed. The claims checked here are about PROSE — that the
// contract says it — not about layout: without this, reflowing a paragraph (or
// putting a word in bold) would break the test without the contract having
// stopped saying anything.
const flat = (s) => s.replace(/\*/g, '').replace(/\s+/g, ' ')

describe('contract §9: what /ct-next does with what you groom', () => {
  it('check: the previous contract said NOTHING of this (the tests below do not pass by accident)', () => {
    expect(V1).not.toMatch(/se salta|no se despacha/i)
    expect(V1).not.toMatch(/--cap/)
    expect(V1).not.toMatch(/heartbeat/i)
    // `cmux` appeared ONCE, in passing ("el nombre del workspace cmux"), never
    // saying what it is nor that you need to have it.
    expect(V1.match(/cmux/gi) || []).toHaveLength(1)
    expect(V1).not.toMatch(/PATH/)
  })

  it('it says a token shared with an active claim BLOCKS (it does not warn): the slice is not dispatched', () => {
    const a = seed()
    // The collision rule stated, not just its vocabulary.
    expect(a).toMatch(/status:in-progress/)
    expect(a).toMatch(/no se despacha|se salta/i)
    // And that ONE shared token is enough.
    expect(a).toMatch(/un solo token|un único token|UN token/i)
  })

  it('it tells the token collision apart from the global serialisation, which are two rules acting at once', () => {
    const a = seed()
    for (const t of SERIALIZING_TOUCHES) expect(a).toContain(t)
    // What makes it DIFFERENT: two slices with different serialising touches
    // share no token at all and even so cannot fly at the same time.
    expect(a).toMatch(/no comparten ning[úu]n token|sin compartir ning[úu]n token/i)
  })

  it('it says `merge-after` means MERGED (the issue closed as completed), neither approved nor in review', () => {
    const a = seed()
    expect(a).toMatch(/merge-after/)
    expect(a).toMatch(/cerrado/i)
    expect(a).toMatch(/aprobad|en review|status:in-review/i)
    // And the consequence that changes decisions: who the bottleneck is.
    expect(a).toMatch(/cuello de botella|bloquea a todos|nada.{0,40}avanza/i)
  })

  it('it says how many slices one invocation dispatches and what it takes to get a window of parallelism', () => {
    const a = seed()
    expect(a).toMatch(/--cap/)
    expect(a).toMatch(/por defecto\s*(es\s*)?`?1`?/i)
    // The cap is GLOBAL (it counts what is already in flight), not a cap per
    // invocation: without this, a second /ct-next looks as if it "does nothing".
    expect(a).toMatch(/en vuelo/i)
  })

  it('it says /ct-next does NOT narrow by epic: it sweeps every epic in the repo and picks by the lowest #', () => {
    const a = seed()
    expect(a).toMatch(/no\s+(hay|tiene)\s+`?--milestone`?/i)
    expect(a).toMatch(/dos epics|dos epic/i)
    // And which lever does exist for choosing which epic advances.
    expect(a).toMatch(/status:ready/)
  })

  it('and it admits that a TIE of # between two epics is undefined, instead of keeping quiet about it', () => {
    // A case nobody asked for, found while reading selectNext: the order is
    // resolved with `.sort((a, b) => a.order - b.order)` over ALL the repo's
    // open issues. With two live epics, two different slices can carry the SAME
    // `#`, and then whichever one GitHub returned first wins. The check below
    // demonstrates it against the real code; the contract cannot promise an
    // order that does not exist.
    const mk = (n, order, t) => ({ n, order, status: 'ready', deps: [], touches: [t], name: `s${n}` })
    expect(selectNext([mk(10, 1, 'ui'), mk(20, 1, 'api')], { concurrencyCap: 1 })[0].n).toBe(10)
    expect(selectNext([mk(20, 1, 'api'), mk(10, 1, 'ui')], { concurrencyCap: 1 })[0].n).toBe(20)
    expect(flat(seed())).toMatch(/no est[áa] definido|sin orden garantizado/i)
  })

  it('it documents cmux: what it is, that it is needed, and what happens if it is not there', () => {
    const a = seed()
    expect(a).toMatch(/cmux/)
    expect(a).toMatch(/PATH/)
    expect(flat(a)).toMatch(/ning[úu]n slice|nada se lanza|no puede lanzar/i)
    // It is not a groom requirement: telling them apart avoids installing it
    // "just in case".
    expect(a).toMatch(/\/ct-groom/)
  })

  it('it says what happens if you interrupt /ct-next and whether re-invoking it is idempotent', () => {
    const a = seed()
    expect(a).toMatch(/Ctrl-C|SIGINT/)
    expect(a).toMatch(/revierte|revertir/i)
    expect(a).toMatch(/idempotent/i)
    // Orphaned worktree/branch: they are detected before claiming, not halfway.
    expect(a).toMatch(/\.worktrees\/<n>/)
    expect(a).toMatch(/feat\/<n>/)
  })

  it('it says the claim is a label with NO heartbeat: a dead slice blocks whoever shares its tokens', () => {
    const a = seed()
    expect(a).toMatch(/heartbeat|caduca|expira/i)
    expect(a).toMatch(/a mano/i)
    // The exact release command, which is what you need at 3 AM.
    expect(a).toMatch(/gh issue edit .*status:ready.*status:in-progress|gh issue edit .*status:in-progress/)
  })

  it('it says every slice in flight has ITS OWN .agent/STATE.md, the one in its worktree', () => {
    const a = seed()
    expect(a).toMatch(/\.worktrees\/<n>\/\.agent\/STATE\.md|\.agent\/STATE\.md.{0,80}worktree/s)
    expect(a).toMatch(/no se pisan|uno por worktree|no comparten/i)
  })

  it('it says what context the dispatched agent receives — and what it does NOT receive', () => {
    const a = seed()
    expect(a).toMatch(/kickoff/i)
    // It hydrates from the ISSUE, not from the spec: what is not in the issue does not arrive.
    expect(flat(a)).toMatch(/no recibe el spec|nunca lee el spec|no lee el spec/i)
    expect(a).toMatch(/Acceptance criteria|criterios de aceptaci/i)
  })

  // #93 — the long reference of `/ct-next` is no longer in
  // `commands/ct-next.md` (which kept the invocation and its table of exit
  // codes): it lives in the plugin repo's `docs/loop/ct-next.md`. The contract
  // has to send you there, because a reference pointing at a file that no
  // longer holds what it promises is worse than none: it looks alive.
  it('it is still a section, not a manual: it sends you to docs/loop/ct-next.md for the invocation reference', () => {
    const a = seed()
    expect(a).toMatch(/docs\/loop\/ct-next\.md/)
    expect(a).not.toMatch(/`commands\/ct-next\.md`/)
  })
})

// ============================================================================
// F13 — the v4 contract PROMISED guarantees the code does not give. This is not
// wording: they are four claims a reader used to take decisions (which tokens
// to put, in what order to merge, what to do with a discarded slice) and that
// were false or incomplete. Each test here ties one correction against an
// executable source when there is one.
// ============================================================================
describe('contract §9 (F13): what it promises matches what the code does', () => {
  it('check: the v4 contract said NOTHING of this (the tests below do not pass by accident)', () => {
    const v4 = historicalBlockV4()
    // The old promise, verbatim: "serializan globalmente… en todo el repo",
    // never saying which set that "todo" comes out of.
    expect(v4).toMatch(/serializan\s+\*\*globalmente\*\*/)
    expect(v4).toMatch(/en todo el repo/)
    expect(flat(v4)).not.toMatch(/solo mira issues de ESTE repo/i)
    // There was no exit from in-review at all: it was a terminal state.
    expect(v4).not.toMatch(/--reopen/)
    // The "not planned" trap WAS there (F11 wrote it); the OPPOSITE one —
    // closing as completed without merging satisfies the dep all the same, and
    // that goes undetected — was not, and on top of that the text suggested the
    // contrary ("cerrado como completado (lo que ocurre al mergear su PR)").
    expect(v4).toMatch(/not planned/)
    expect(v4).not.toMatch(/no se detecta/i)
    expect(flat(v4)).toMatch(/lo que ocurre al mergear su PR/)
    // And the collision rule spoke ONLY of in-progress.
    expect(flat(v4)).not.toMatch(/in-progress o status:in-review/i)
    expect(v4).not.toMatch(/compare-and-swap/)
  })

  it('it says the REAL SCOPE of the serialisation: the issues of this repo, not "todo el repo"', () => {
    // The code (dispatch.js#collectTokenHolders + ct-next.mjs#loadIssues) only
    // looks at issues of THIS repo with status in-progress/in-review. Another
    // branch, another track, or a human doing it by hand are invisible — the
    // contract sold it as a global guarantee.
    const a = flat(seed())
    expect(a).toMatch(/solo mira issues de ESTE repo/i)
    expect(a).toMatch(/status:in-progress/)
    expect(a).toMatch(/INVISIBLE|invisible/)
    expect(a).toMatch(/global al flujo de issues de este repo/i)
  })

  it('it says a token is held until the MERGE, and that in-review blocks too', () => {
    const a = flat(seed())
    expect(a).toMatch(/status:in-review/)
    expect(a).toMatch(/hasta que el PR se mergea|retiene.{0,60}hasta el merge/i)
    // And the practical consequence that changes how you design the table.
    expect(a).toMatch(/un PR sin mergear frena a sus vecinos de área/i)
    // Check against the code: a ready that shares a token with an in-review is
    // NOT selected. If this stopped being true, the contract would be lying.
    const holder = { n: 1, order: 1, status: 'in-review', deps: [], touches: ['api'] }
    const cand = { n: 2, order: 2, status: 'ready', deps: [], touches: ['api'] }
    expect(planDispatch([holder, cand], { mergedIssues: [], cap: 5 }).selected).toEqual([])
  })

  it('it says in-review does NOT take up cap, which is the other half of the rule', () => {
    const a = flat(seed())
    expect(a).toMatch(/`?status:in-review`? \*?\*?no\*?\*? ocupa cap|no.{0,20}ocupa cap/i)
    // Check against the code: with cap 1 and an in-review holding somebody
    // else's tokens, the ready DOES come out.
    const holder = { n: 1, order: 1, status: 'in-review', deps: [], touches: ['api'] }
    const cand = { n: 2, order: 2, status: 'ready', deps: [], touches: ['ui'] }
    expect(planDispatch([holder, cand], { mergedIssues: [], cap: 1 }).selected.map((i) => i.n)).toEqual([2])
  })

  it('it enumerates the TWO traps of "cerrado ≠ mergeado" — and the second is no longer waved away as "no se detecta" (F18)', () => {
    const a = flat(seed())
    expect(a).toMatch(/not planned/)
    expect(a).toMatch(/para siempre/i)
    // The opposite direction is still enumerated…
    expect(a).toMatch(/completed.{0,200}sin que se haya mergeado|sin que se haya mergeado.{0,200}completed/i)
    // …but F18 falsified BOTH halves of the excuse with which v7 left it out
    // ("no se detecta" + "haría falta cruzar el grafo de PRs"): it happens by
    // accident (a closing keyword in ANY commit, quotes included) and a single
    // query resolves 97 issues. The contract can no longer say either of the
    // two.
    expect(a).not.toMatch(/haría falta cruzar el grafo de PRs/i)
    expect(a).toMatch(/cualquier mensaje de commit/i)
    expect(a).toMatch(/las comillas no protegen/i)
  })

  it('it documents the exit from in-review for a rejected PR, with the command', () => {
    const a = seed()
    expect(a).toMatch(/--reopen/)
    expect(flat(a)).toMatch(/no es un estado terminal|NO\*?\*? es un estado terminal/i)
    // The two paths with the worktree/branch that already exist — without this,
    // reopening "works" and the next /ct-next refuses without explaining why.
    expect(a).toMatch(/\.worktrees\/<n>/)
    expect(a).toMatch(/feat\/<n>/)
    expect(flat(a)).toMatch(/corregir encima/i)
    expect(flat(a)).toMatch(/empezar de cero/i)
  })

  it('it admits the collision and the cap only hold for ONE dispatcher at a time', () => {
    // The claim is a label with no compare-and-swap: two concurrent /ct-next
    // can claim the same token. It was said in commands/ct-next.md but NOT in
    // the contract, which is the file read by whoever writes the table and
    // decides the tokens.
    const a = flat(seed())
    expect(a).toMatch(/compare-and-swap/i)
    expect(a).toMatch(/no lances dos dispatchers a la vez/i)
  })

  it('the footnote declares the SAME version as the marker of the block', () => {
    // The v4 declared `<!-- ct-init:slices-contract-version: 4 -->` and its
    // footnote said "contrato v3": the number a human sees and the one the
    // script reads had been a whole version out of sync.
    const a = seed()
    const marker = a.match(/<!-- ct-init:slices-contract-version: (\d+) -->/)
    const footer = a.match(/Este contrato lo mantiene `\/ct-init` \(contrato v(\d+)\)/)
    expect(marker).not.toBeNull()
    expect(footer).not.toBeNull()
    expect(footer[1]).toBe(marker[1])
  })
})

// ============================================================================
// F15 — two corrections that a repo already bootstrapped cannot work out on its
// own. The v5 → v6 bump is the only lever that gets them to it.
// ============================================================================
describe('contract §9 (F15): the return of a rejected PR and the order of /ct-groom', () => {
  it('check: the v5 contract said exactly the opposite on both counts', () => {
    const v5 = historicalBlockV5()
    // (1) --reopen went to `ready`, and it was sold as "vuelve a ser
    // despachable".
    expect(flat(v5)).toMatch(/lo mueve `?in-review`? → `?ready`?/i)
    expect(v5).not.toMatch(/--requeue/)
    // (2) the order of /ct-groom WAS stated — and it told the truth of the
    // time: that the milestone and the labels could be left created. Which is
    // to say the contract was not keeping a guarantee quiet, it was documenting
    // with precision one that was worse. What changes in F15 is the CODE; the
    // text comes along behind.
    expect(flat(v5)).toMatch(/el milestone y las labels sí pueden haberse creado ya/i)
    expect(flat(v5)).not.toMatch(/sin haber creado nada/i)
  })

  it('it says --reopen leaves the slice at in-progress and that it STILL holds tokens', () => {
    const a = flat(seed())
    expect(a).toMatch(/in-review`? → `?in-progress/i)
    expect(a).toMatch(/sigue reteniendo sus tokens/i)
    // The consequence that changes what you do: reopening frees nobody.
    expect(a).toMatch(/no desbloquea a sus vecinos/i)
    // Check against the code: a ready that shares a token with the reopened one
    // (already at in-progress) is NOT selected, not even with cap to spare.
    const reopened = { n: 1, order: 1, status: 'in-progress', deps: [], touches: ['api'] }
    const neighbour = { n: 2, order: 2, status: 'ready', deps: [], touches: ['api'] }
    expect(planDispatch([reopened, neighbour], { mergedIssues: [], cap: 5 }).selected).toEqual([])
  })

  it('it documents --requeue as the only transition that releases tokens without a merge, and what it checks', () => {
    const a = seed()
    expect(a).toMatch(/--requeue/)
    const f = flat(a)
    expect(f).toMatch(/in-progress`? → `?ready/i)
    expect(f).toMatch(/no se declara ausente lo que no se ha visto/i)
    // And what it CANNOT check, said instead of kept quiet.
    expect(f).toMatch(/la rama en el remoto y el PR abierto/i)
  })

  it('it says /ct-groom validates the Project BEFORE creating anything, and that there is no transaction', () => {
    const f = flat(seed())
    expect(f).toMatch(/aborta sin haber creado nada/i)
    expect(f).toMatch(/Todo lo que .{0,20}ct-groom.{0,20} LEE ocurre antes de todo lo que ESCRIBE/i)
    // The other half, the one that is NOT promised: it has to be said too.
    expect(f).toMatch(/no hay transacción/i)
    expect(f).toMatch(/idempotente/i)
  })
})
